title:              make IT work
email:              mateusz@gepert.info
description:        Technical, philosophical, nostalgic not always about jvm
author:             Mateusz Gepert
url:                "https://mateuszgepert.github.io"
future:             true

# Social Profiles
twitter_username:
github_username:    mateuszgepert
facebook_username:
instagram_username:
linkedin_username: mateusz-gepert

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
highlighter:        rouge
input:              GFM
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
